5X: Disable the log_lock_waits feature
This is a backport of 6X commit 3763cc7379b with minor conflicts
resolved. Original commit message follows:

log_lock_waits was never officially supported and it was missing from
our official documentation. This commit disallows the GUC from being
set. Setting the GUC to on will be a no-op with a WARNING emitted.

The reason why we can't support this GUC boils down to inconsistencies
between ResProcSleep() and its upstream equivalent ProcSleep().
ResProcSleep() clearly did not get the memo about log_lock_waits.
(introduced in e52c4a6e26f, much after resource queues were incepted)

The way the GUC works is simple: When anything other than a hard
deadlock is detected in CheckDeadlock(), the waiting process wakes up
inside ProcSleep(), logs the lock wait, and then goes back to sleep.

Unlike ProcSleep(), if a process is waiting on a resource queue in
ResProcSleep(), after waking up, we don't log the lock wait. That's not
all - the code flow leads to a spurious and possibly empty (no errdetail
capturing deadlock info) deadlock report. This is because
MyProc->waitStatus is still set to STATUS_ERROR after the wakeup in
ResProcSleep().

The spurious deadlock report has further ramifications.

1) Unlike we would in a hard deadlock report, we don't call
ResRemoveFromWaitQueue(). This has adverse consequences:

a) The PGPROC entry for the backend is not removed from the resource
queue lock's wait queue (waitProcs). Now, the same PGPROC entry will be
recycled and used for another backend after this backend exits. So, the
waitProcs link will be dangling and segfaults can result whenever the
waitProcs list is traversed (such as ResProcLockRemoveSelfAndWakeup(),
FindLockCycleRecurse() etc).

b) The portal increment is not removed. This can lead to:
WARNING: duplicate portal id <> for proc <>
and a misleading ERROR which follows immediately after:
ERROR: out of shared memory adding portal increments
for the same process, on a subsequent ResLockAcquire().

2) We don't clean up the locallock, opening up a possibility for the
same memory corruption scenario as the one fixed in f8348f911b1.

Note: Fixing the misleading out of shared memory message is left for a
later commit.

(cherry picked from commit 3763cc7379b274f4a60b91dc5f53c74b5facc252)